<?php
$putter_slider_sc = putter_get_theme_option( 'front_page_title_shortcode' );
if ( ! empty( $putter_slider_sc ) && strpos( $putter_slider_sc, '[' ) !== false && strpos( $putter_slider_sc, ']' ) !== false ) {

	?><div class="front_page_section front_page_section_title front_page_section_slider front_page_section_title_slider
		<?php
		if ( putter_get_theme_option( 'front_page_title_stack' ) ) {
			echo ' sc_stack_section_on';
		}
		?>
	">
	<?php
		// Add anchor
		$putter_anchor_icon = putter_get_theme_option( 'front_page_title_anchor_icon' );
		$putter_anchor_text = putter_get_theme_option( 'front_page_title_anchor_text' );
	if ( ( ! empty( $putter_anchor_icon ) || ! empty( $putter_anchor_text ) ) && shortcode_exists( 'trx_sc_anchor' ) ) {
		echo do_shortcode(
			'[trx_sc_anchor id="front_page_section_title"'
									. ( ! empty( $putter_anchor_icon ) ? ' icon="' . esc_attr( $putter_anchor_icon ) . '"' : '' )
									. ( ! empty( $putter_anchor_text ) ? ' title="' . esc_attr( $putter_anchor_text ) . '"' : '' )
									. ']'
		);
	}
		// Show slider (or any other content, generated by shortcode)
		echo do_shortcode( $putter_slider_sc );
	?>
	</div>
	<?php

} else {

	?>
	<div class="front_page_section front_page_section_title
		<?php
		$putter_scheme = putter_get_theme_option( 'front_page_title_scheme' );
		if ( ! empty( $putter_scheme ) && ! putter_is_inherit( $putter_scheme ) ) {
			echo ' scheme_' . esc_attr( $putter_scheme );
		}
		echo ' front_page_section_paddings_' . esc_attr( putter_get_theme_option( 'front_page_title_paddings' ) );
		if ( putter_get_theme_option( 'front_page_title_stack' ) ) {
			echo ' sc_stack_section_on';
		}
		?>
		"
		<?php
		$putter_css      = '';
		$putter_bg_image = putter_get_theme_option( 'front_page_title_bg_image' );
		if ( ! empty( $putter_bg_image ) ) {
			$putter_css .= 'background-image: url(' . esc_url( putter_get_attachment_url( $putter_bg_image ) ) . ');';
		}
		if ( ! empty( $putter_css ) ) {
			echo ' style="' . esc_attr( $putter_css ) . '"';
		}
		?>
	>
	<?php
		// Add anchor
		$putter_anchor_icon = putter_get_theme_option( 'front_page_title_anchor_icon' );
		$putter_anchor_text = putter_get_theme_option( 'front_page_title_anchor_text' );
	if ( ( ! empty( $putter_anchor_icon ) || ! empty( $putter_anchor_text ) ) && shortcode_exists( 'trx_sc_anchor' ) ) {
		echo do_shortcode(
			'[trx_sc_anchor id="front_page_section_title"'
									. ( ! empty( $putter_anchor_icon ) ? ' icon="' . esc_attr( $putter_anchor_icon ) . '"' : '' )
									. ( ! empty( $putter_anchor_text ) ? ' title="' . esc_attr( $putter_anchor_text ) . '"' : '' )
									. ']'
		);
	}
	?>
		<div class="front_page_section_inner front_page_section_title_inner
		<?php
		if ( putter_get_theme_option( 'front_page_title_fullheight' ) ) {
			echo ' putter-full-height sc_layouts_flex sc_layouts_columns_middle';
		}
		?>
			"
			<?php
			$putter_css      = '';
			$putter_bg_mask  = putter_get_theme_option( 'front_page_title_bg_mask' );
			$putter_bg_color_type = putter_get_theme_option( 'front_page_title_bg_color_type' );
			if ( 'custom' == $putter_bg_color_type ) {
				$putter_bg_color = putter_get_theme_option( 'front_page_title_bg_color' );
			} elseif ( 'scheme_bg_color' == $putter_bg_color_type ) {
				$putter_bg_color = putter_get_scheme_color( 'bg_color', $putter_scheme );
			} else {
				$putter_bg_color = '';
			}
			if ( ! empty( $putter_bg_color ) && $putter_bg_mask > 0 ) {
				$putter_css .= 'background-color: ' . esc_attr(
					1 == $putter_bg_mask ? $putter_bg_color : putter_hex2rgba( $putter_bg_color, $putter_bg_mask )
				) . ';';
			}
			if ( ! empty( $putter_css ) ) {
				echo ' style="' . esc_attr( $putter_css ) . '"';
			}
			?>
		>
			<div class="front_page_section_content_wrap front_page_section_title_content_wrap content_wrap">
				<?php
				// Caption
				$putter_caption = putter_get_theme_option( 'front_page_title_caption' );
				if ( ! empty( $putter_caption ) || ( current_user_can( 'edit_theme_options' ) && is_customize_preview() ) ) {
					?>
					<h1 class="front_page_section_caption front_page_section_title_caption front_page_block_<?php echo ! empty( $putter_caption ) ? 'filled' : 'empty'; ?>"><?php echo wp_kses( $putter_caption, 'putter_kses_content' ); ?></h1>
					<?php
				}

				// Description (text)
				$putter_description = putter_get_theme_option( 'front_page_title_description' );
				if ( ! empty( $putter_description ) || ( current_user_can( 'edit_theme_options' ) && is_customize_preview() ) ) {
					?>
					<div class="front_page_section_description front_page_section_title_description front_page_block_<?php echo ! empty( $putter_description ) ? 'filled' : 'empty'; ?>"><?php echo wp_kses( wpautop( $putter_description ), 'putter_kses_content' ); ?></div>
					<?php
				}

				// Buttons
				if ( putter_get_theme_option( 'front_page_title_button1_link' ) != '' || putter_get_theme_option( 'front_page_title_button2_link' ) != '' ) {
					?>
					<div class="front_page_section_buttons front_page_section_title_buttons">
					<?php
						putter_show_layout( putter_customizer_partial_refresh_front_page_title_button1_link() );
						putter_show_layout( putter_customizer_partial_refresh_front_page_title_button2_link() );
					?>
					</div>
					<?php
				}
				?>
			</div>
		</div>
	</div>
	<?php
}
